apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
# Define ReplicaSet
spec:
  replicas: 3
  # Deployment strategy "rolling update"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  # Match Pods with this label
  selector:
    matchLabels:
      app: nodejs-app
  # Define Pod template for ReplicaSet
  template:
    metadata:
      # Label to match to ReplicaSet
      labels:
        app: nodejs-app
    # Define Container in Pod
    spec:
      containers:
        - name: my-app
          image: joska99/node-app:latest
          # Define resources limits for container
          resources:
            # Scrap metrics
            requests:
              cpu: 200m
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
