apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  # Attach to pods by label
  selector:
    app: nodejs-app
  ports:
    - port: 8000
      targetPort: 8000
      #  32000+ port range
      nodePort: 32000
