version: "3"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: "jenkins-controller"
    restart: "on-failure"
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
